using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.TransportationSetSupplierViewTemplates
{
    public class TransportationSetSupplierViewTemplateManager : TransportationSetSupplierViewTemplateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetSupplierViewTemplateManager(ITransportationSetSupplierViewTemplateRepository transportationSetSupplierViewTemplateRepository)
            : base(transportationSetSupplierViewTemplateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}