using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.TransportationSetSupplierViewTemplates
{
    public class TransportationSetSupplierViewTemplate : TransportationSetSupplierViewTemplateBase
    {
        //<suite-custom-code-autogenerated>
        protected TransportationSetSupplierViewTemplate()
        {

        }

        public TransportationSetSupplierViewTemplate(Guid id, Guid? supplierTenantId = null, Guid? transportationSetViewTemplateRootId = null, Guid? supplierId = null, Guid? rootId = null, Guid? shippingRootId = null)
            : base(id, supplierTenantId, transportationSetViewTemplateRootId, supplierId, rootId, shippingRootId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}