using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.ChatGroups
{
    public class ChatGroupManager : ChatGroupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ChatGroupManager(IChatGroupRepository chatGroupRepository)
            : base(chatGroupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}