using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.ChatGroups
{
    public class ChatGroup : ChatGroupBase
    {
        //<suite-custom-code-autogenerated>
        protected ChatGroup()
        {

        }

        public ChatGroup(Guid id, bool isActive, string? name = null, string? description = null, string? providerName = null, Guid? providerKey = null)
            : base(id, isActive, name, description, providerName, providerKey)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}