using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.TransportationSetItems;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.TransportationSetItems
{
    public class TransportationSetItemsAppService : TransportationSetItemsAppServiceBase, ITransportationSetItemsAppService
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetItemsAppService(ITransportationSetItemRepository transportationSetItemRepository, TransportationSetItemManager transportationSetItemManager, IDistributedCache<TransportationSetItemDownloadTokenCacheItem, string> downloadTokenCache)
            : base(transportationSetItemRepository, transportationSetItemManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}