using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.TransportationSetItems
{
    public class TransportationSetItem : TransportationSetItemBase
    {
        //<suite-custom-code-autogenerated>
        protected TransportationSetItem()
        {

        }

        public TransportationSetItem(Guid id, int order, bool isActive, bool isDefault, string? name = null, string? type = null, string? attributes = null, string? category = null, Guid? rootId = null, Guid? transportationSetRootId = null, Guid? transportationSetItemGroupRootId = null)
            : base(id, order, isActive, isDefault, name, type, attributes, category, rootId, transportationSetRootId, transportationSetItemGroupRootId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}