using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.TransportationSetItems
{
    public class TransportationSetItemManager : TransportationSetItemManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetItemManager(ITransportationSetItemRepository transportationSetItemRepository)
            : base(transportationSetItemRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}