using PortX.TransportationSetItemGroups;
using Xunit;

namespace PortX.EntityFrameworkCore.Applications.TransportationSetItemGroups;

public class EfCoreTransportationSetItemGroupsAppServiceTests : TransportationSetItemGroupsAppServiceTests<PortXEntityFrameworkCoreTestModule>
{
}