using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.TransportationSetViewTemplates
{
    public class TransportationSetViewTemplateManager : TransportationSetViewTemplateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetViewTemplateManager(ITransportationSetViewTemplateRepository transportationSetViewTemplateRepository)
            : base(transportationSetViewTemplateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}