using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.TransportationSetViewTemplates
{
    public class TransportationSetViewTemplate : TransportationSetViewTemplateBase
    {
        //<suite-custom-code-autogenerated>
        protected TransportationSetViewTemplate()
        {

        }

        public TransportationSetViewTemplate(Guid id, string? name = null, string? description = null, string? data = null, Guid? rootId = null, Guid? transportationSetRootId = null)
            : base(id, name, description, data, rootId, transportationSetRootId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}