using System;

namespace PortX.TransportationSetSupplierViewTemplates;

[Serializable]
public class TransportationSetSupplierViewTemplateDownloadTokenCacheItem : TransportationSetSupplierViewTemplateDownloadTokenCacheItemBase
{
}