using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.TransportationSetSupplierViewTemplates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.TransportationSetSupplierViewTemplates
{
    public class TransportationSetSupplierViewTemplatesAppService : TransportationSetSupplierViewTemplatesAppServiceBase, ITransportationSetSupplierViewTemplatesAppService
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetSupplierViewTemplatesAppService(ITransportationSetSupplierViewTemplateRepository transportationSetSupplierViewTemplateRepository, TransportationSetSupplierViewTemplateManager transportationSetSupplierViewTemplateManager, IDistributedCache<TransportationSetSupplierViewTemplateDownloadTokenCacheItem, string> downloadTokenCache)
            : base(transportationSetSupplierViewTemplateRepository, transportationSetSupplierViewTemplateManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}