using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.ChatGroups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.ChatGroups
{
    public class ChatGroupsAppService : ChatGroupsAppServiceBase, IChatGroupsAppService
    {
        //<suite-custom-code-autogenerated>
        public ChatGroupsAppService(IChatGroupRepository chatGroupRepository, ChatGroupManager chatGroupManager, IDistributedCache<ChatGroupDownloadTokenCacheItem, string> downloadTokenCache)
            : base(chatGroupRepository, chatGroupManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}