using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.ShippingWorkflows;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.ShippingWorkflows
{
    public class ShippingWorkflowsAppService : ShippingWorkflowsAppServiceBase, IShippingWorkflowsAppService
    {
        //<suite-custom-code-autogenerated>
        public ShippingWorkflowsAppService(IShippingWorkflowRepository shippingWorkflowRepository, ShippingWorkflowManager shippingWorkflowManager, IDistributedCache<ShippingWorkflowDownloadTokenCacheItem, string> downloadTokenCache)
            : base(shippingWorkflowRepository, shippingWorkflowManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}