using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.ShippingWorkflows
{
    public class ShippingWorkflowManager : ShippingWorkflowManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ShippingWorkflowManager(IShippingWorkflowRepository shippingWorkflowRepository)
            : base(shippingWorkflowRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}