using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.ShippingWorkflows
{
    public class ShippingWorkflow : ShippingWorkflowBase
    {
        //<suite-custom-code-autogenerated>
        protected ShippingWorkflow()
        {

        }

        public ShippingWorkflow(Guid id, bool isActive, string? name = null, string? transportationType = null, string? mode = null, string? incoterms = null, string? conditionSettings = null, Guid? rootId = null, Guid? transportationSetRootId = null)
            : base(id, isActive, name, transportationType, mode, incoterms, conditionSettings, rootId, transportationSetRootId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}