using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.TransportationSetItemGroups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.TransportationSetItemGroups
{
    public class TransportationSetItemGroupsAppService : TransportationSetItemGroupsAppServiceBase, ITransportationSetItemGroupsAppService
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetItemGroupsAppService(ITransportationSetItemGroupRepository transportationSetItemGroupRepository, TransportationSetItemGroupManager transportationSetItemGroupManager, IDistributedCache<TransportationSetItemGroupDownloadTokenCacheItem, string> downloadTokenCache)
            : base(transportationSetItemGroupRepository, transportationSetItemGroupManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}