using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortX.TransportationSetItemGroups
{
    public class TransportationSetItemGroupManager : TransportationSetItemGroupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetItemGroupManager(ITransportationSetItemGroupRepository transportationSetItemGroupRepository)
            : base(transportationSetItemGroupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}