using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace PortX.TransportationSetItemGroups
{
    public class TransportationSetItemGroup : TransportationSetItemGroupBase
    {
        //<suite-custom-code-autogenerated>
        protected TransportationSetItemGroup()
        {

        }

        public TransportationSetItemGroup(Guid id, string? name = null, int? order = null, string? type = null, Guid? rootId = null, Guid? transportationSetRootId = null)
            : base(id, name, order, type, rootId, transportationSetRootId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}