using PortX.TransportationSetViewTemplates;
using Xunit;

namespace PortX.EntityFrameworkCore.Applications.TransportationSetViewTemplates;

public class EfCoreTransportationSetViewTemplatesAppServiceTests : TransportationSetViewTemplatesAppServiceTests<PortXEntityFrameworkCoreTestModule>
{
}