using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortX.Permissions;
using PortX.TransportationSetViewTemplates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using PortX.Shared;

namespace PortX.TransportationSetViewTemplates
{
    public class TransportationSetViewTemplatesAppService : TransportationSetViewTemplatesAppServiceBase, ITransportationSetViewTemplatesAppService
    {
        //<suite-custom-code-autogenerated>
        public TransportationSetViewTemplatesAppService(ITransportationSetViewTemplateRepository transportationSetViewTemplateRepository, TransportationSetViewTemplateManager transportationSetViewTemplateManager, IDistributedCache<TransportationSetViewTemplateDownloadTokenCacheItem, string> downloadTokenCache)
            : base(transportationSetViewTemplateRepository, transportationSetViewTemplateManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}